/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CleanupRouteImport } from './routes/cleanup'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as CleanupIndexRouteImport } from './routes/cleanup.index'
import { Route as CleanupSectionRouteImport } from './routes/cleanup.$section'
import { Route as CleanupConfirmRouteImport } from './routes/cleanup.confirm'
import { Route as CleanupFreeRouteImport } from './routes/cleanup.free'
import { Route as StorageSplatRouteImport } from './routes/storage.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanupRoute = CleanupRouteImport.update({
  id: '/cleanup',
  path: '/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanupIndexRoute = CleanupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CleanupRoute,
} as any)
const CleanupSectionRoute = CleanupSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => CleanupRoute,
} as any)
const CleanupConfirmRoute = CleanupConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => CleanupRoute,
} as any)
const CleanupFreeRoute = CleanupFreeRouteImport.update({
  id: '/free',
  path: '/free',
  getParentRoute: () => CleanupRoute,
} as any)
const StorageSplatRoute = StorageSplatRouteImport.update({
  id: '/storage/$',
  path: '/storage/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cleanup': typeof CleanupRouteWithChildren
  '/insights': typeof InsightsRoute
  '/cleanup/$section': typeof CleanupSectionRoute
  '/cleanup/confirm': typeof CleanupConfirmRoute
  '/cleanup/free': typeof CleanupFreeRoute
  '/storage/$': typeof StorageSplatRoute
  '/cleanup/': typeof CleanupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/cleanup/$section': typeof CleanupSectionRoute
  '/cleanup/confirm': typeof CleanupConfirmRoute
  '/cleanup/free': typeof CleanupFreeRoute
  '/storage/$': typeof StorageSplatRoute
  '/cleanup': typeof CleanupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cleanup': typeof CleanupRouteWithChildren
  '/insights': typeof InsightsRoute
  '/cleanup/$section': typeof CleanupSectionRoute
  '/cleanup/confirm': typeof CleanupConfirmRoute
  '/cleanup/free': typeof CleanupFreeRoute
  '/storage/$': typeof StorageSplatRoute
  '/cleanup/': typeof CleanupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cleanup'
    | '/insights'
    | '/cleanup/$section'
    | '/cleanup/confirm'
    | '/cleanup/free'
    | '/storage/$'
    | '/cleanup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/insights'
    | '/cleanup/$section'
    | '/cleanup/confirm'
    | '/cleanup/free'
    | '/storage/$'
    | '/cleanup'
  id:
    | '__root__'
    | '/'
    | '/cleanup'
    | '/insights'
    | '/cleanup/$section'
    | '/cleanup/confirm'
    | '/cleanup/free'
    | '/storage/$'
    | '/cleanup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CleanupRoute: typeof CleanupRouteWithChildren
  InsightsRoute: typeof InsightsRoute
  StorageSplatRoute: typeof StorageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleanup': {
      id: '/cleanup'
      path: '/cleanup'
      fullPath: '/cleanup'
      preLoaderRoute: typeof CleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleanup/': {
      id: '/cleanup/'
      path: '/'
      fullPath: '/cleanup/'
      preLoaderRoute: typeof CleanupIndexRouteImport
      parentRoute: typeof CleanupRoute
    }
    '/cleanup/$section': {
      id: '/cleanup/$section'
      path: '/$section'
      fullPath: '/cleanup/$section'
      preLoaderRoute: typeof CleanupSectionRouteImport
      parentRoute: typeof CleanupRoute
    }
    '/cleanup/confirm': {
      id: '/cleanup/confirm'
      path: '/confirm'
      fullPath: '/cleanup/confirm'
      preLoaderRoute: typeof CleanupConfirmRouteImport
      parentRoute: typeof CleanupRoute
    }
    '/cleanup/free': {
      id: '/cleanup/free'
      path: '/free'
      fullPath: '/cleanup/free'
      preLoaderRoute: typeof CleanupFreeRouteImport
      parentRoute: typeof CleanupRoute
    }
    '/storage/$': {
      id: '/storage/$'
      path: '/storage/$'
      fullPath: '/storage/$'
      preLoaderRoute: typeof StorageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CleanupRouteChildren {
  CleanupSectionRoute: typeof CleanupSectionRoute
  CleanupConfirmRoute: typeof CleanupConfirmRoute
  CleanupFreeRoute: typeof CleanupFreeRoute
  CleanupIndexRoute: typeof CleanupIndexRoute
}

const CleanupRouteChildren: CleanupRouteChildren = {
  CleanupSectionRoute: CleanupSectionRoute,
  CleanupConfirmRoute: CleanupConfirmRoute,
  CleanupFreeRoute: CleanupFreeRoute,
  CleanupIndexRoute: CleanupIndexRoute,
}

const CleanupRouteWithChildren =
  CleanupRoute._addFileChildren(CleanupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CleanupRoute: CleanupRouteWithChildren,
  InsightsRoute: InsightsRoute,
  StorageSplatRoute: StorageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
