/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as TabsCleanupRouteImport } from './routes/_tabs/cleanup'
import { Route as TabsInsightsRouteImport } from './routes/_tabs/insights'
import { Route as TabsStorageRouteImport } from './routes/_tabs/storage'
import { Route as TabsCleanupIndexRouteImport } from './routes/_tabs/cleanup.index'
import { Route as TabsCleanupSectionRouteImport } from './routes/_tabs/cleanup.$section'
import { Route as TabsStorageIndexRouteImport } from './routes/_tabs/storage.index'
import { Route as TabsStorageSplatRouteImport } from './routes/_tabs/storage.$'
import { Route as TabsCleanupSectionConfirmRouteImport } from './routes/_tabs/cleanup.$section.confirm'
import { Route as TabsCleanupSectionFreeRouteImport } from './routes/_tabs/cleanup.$section.free'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsCleanupRoute = TabsCleanupRouteImport.update({
  id: '/cleanup',
  path: '/cleanup',
  getParentRoute: () => TabsRoute,
} as any)
const TabsInsightsRoute = TabsInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => TabsRoute,
} as any)
const TabsStorageRoute = TabsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => TabsRoute,
} as any)
const TabsCleanupIndexRoute = TabsCleanupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsCleanupRoute,
} as any)
const TabsCleanupSectionRoute = TabsCleanupSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => TabsCleanupRoute,
} as any)
const TabsStorageIndexRoute = TabsStorageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsStorageRoute,
} as any)
const TabsStorageSplatRoute = TabsStorageSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => TabsStorageRoute,
} as any)
const TabsCleanupSectionConfirmRoute =
  TabsCleanupSectionConfirmRouteImport.update({
    id: '/confirm',
    path: '/confirm',
    getParentRoute: () => TabsCleanupSectionRoute,
  } as any)
const TabsCleanupSectionFreeRoute = TabsCleanupSectionFreeRouteImport.update({
  id: '/free',
  path: '/free',
  getParentRoute: () => TabsCleanupSectionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cleanup': typeof TabsCleanupRouteWithChildren
  '/insights': typeof TabsInsightsRoute
  '/storage': typeof TabsStorageRouteWithChildren
  '/cleanup/$section': typeof TabsCleanupSectionRouteWithChildren
  '/storage/$': typeof TabsStorageSplatRoute
  '/cleanup/': typeof TabsCleanupIndexRoute
  '/storage/': typeof TabsStorageIndexRoute
  '/cleanup/$section/confirm': typeof TabsCleanupSectionConfirmRoute
  '/cleanup/$section/free': typeof TabsCleanupSectionFreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insights': typeof TabsInsightsRoute
  '/cleanup/$section': typeof TabsCleanupSectionRouteWithChildren
  '/storage/$': typeof TabsStorageSplatRoute
  '/cleanup': typeof TabsCleanupIndexRoute
  '/storage': typeof TabsStorageIndexRoute
  '/cleanup/$section/confirm': typeof TabsCleanupSectionConfirmRoute
  '/cleanup/$section/free': typeof TabsCleanupSectionFreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteWithChildren
  '/_tabs/cleanup': typeof TabsCleanupRouteWithChildren
  '/_tabs/insights': typeof TabsInsightsRoute
  '/_tabs/storage': typeof TabsStorageRouteWithChildren
  '/_tabs/cleanup/$section': typeof TabsCleanupSectionRouteWithChildren
  '/_tabs/storage/$': typeof TabsStorageSplatRoute
  '/_tabs/cleanup/': typeof TabsCleanupIndexRoute
  '/_tabs/storage/': typeof TabsStorageIndexRoute
  '/_tabs/cleanup/$section/confirm': typeof TabsCleanupSectionConfirmRoute
  '/_tabs/cleanup/$section/free': typeof TabsCleanupSectionFreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cleanup'
    | '/insights'
    | '/storage'
    | '/cleanup/$section'
    | '/storage/$'
    | '/cleanup/'
    | '/storage/'
    | '/cleanup/$section/confirm'
    | '/cleanup/$section/free'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/insights'
    | '/cleanup/$section'
    | '/storage/$'
    | '/cleanup'
    | '/storage'
    | '/cleanup/$section/confirm'
    | '/cleanup/$section/free'
  id:
    | '__root__'
    | '/'
    | '/_tabs'
    | '/_tabs/cleanup'
    | '/_tabs/insights'
    | '/_tabs/storage'
    | '/_tabs/cleanup/$section'
    | '/_tabs/storage/$'
    | '/_tabs/cleanup/'
    | '/_tabs/storage/'
    | '/_tabs/cleanup/$section/confirm'
    | '/_tabs/cleanup/$section/free'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRoute: typeof TabsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/cleanup': {
      id: '/_tabs/cleanup'
      path: '/cleanup'
      fullPath: '/cleanup'
      preLoaderRoute: typeof TabsCleanupRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/insights': {
      id: '/_tabs/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof TabsInsightsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/storage': {
      id: '/_tabs/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof TabsStorageRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/cleanup/': {
      id: '/_tabs/cleanup/'
      path: '/'
      fullPath: '/cleanup/'
      preLoaderRoute: typeof TabsCleanupIndexRouteImport
      parentRoute: typeof TabsCleanupRoute
    }
    '/_tabs/cleanup/$section': {
      id: '/_tabs/cleanup/$section'
      path: '/$section'
      fullPath: '/cleanup/$section'
      preLoaderRoute: typeof TabsCleanupSectionRouteImport
      parentRoute: typeof TabsCleanupRoute
    }
    '/_tabs/storage/': {
      id: '/_tabs/storage/'
      path: '/'
      fullPath: '/storage/'
      preLoaderRoute: typeof TabsStorageIndexRouteImport
      parentRoute: typeof TabsStorageRoute
    }
    '/_tabs/storage/$': {
      id: '/_tabs/storage/$'
      path: '/$'
      fullPath: '/storage/$'
      preLoaderRoute: typeof TabsStorageSplatRouteImport
      parentRoute: typeof TabsStorageRoute
    }
    '/_tabs/cleanup/$section/confirm': {
      id: '/_tabs/cleanup/$section/confirm'
      path: '/confirm'
      fullPath: '/cleanup/$section/confirm'
      preLoaderRoute: typeof TabsCleanupSectionConfirmRouteImport
      parentRoute: typeof TabsCleanupSectionRoute
    }
    '/_tabs/cleanup/$section/free': {
      id: '/_tabs/cleanup/$section/free'
      path: '/free'
      fullPath: '/cleanup/$section/free'
      preLoaderRoute: typeof TabsCleanupSectionFreeRouteImport
      parentRoute: typeof TabsCleanupSectionRoute
    }
  }
}

interface TabsCleanupSectionRouteChildren {
  TabsCleanupSectionConfirmRoute: typeof TabsCleanupSectionConfirmRoute
  TabsCleanupSectionFreeRoute: typeof TabsCleanupSectionFreeRoute
}

const TabsCleanupSectionRouteChildren: TabsCleanupSectionRouteChildren = {
  TabsCleanupSectionConfirmRoute: TabsCleanupSectionConfirmRoute,
  TabsCleanupSectionFreeRoute: TabsCleanupSectionFreeRoute,
}

const TabsCleanupSectionRouteWithChildren =
  TabsCleanupSectionRoute._addFileChildren(TabsCleanupSectionRouteChildren)

interface TabsCleanupRouteChildren {
  TabsCleanupSectionRoute: typeof TabsCleanupSectionRouteWithChildren
  TabsCleanupIndexRoute: typeof TabsCleanupIndexRoute
}

const TabsCleanupRouteChildren: TabsCleanupRouteChildren = {
  TabsCleanupSectionRoute: TabsCleanupSectionRouteWithChildren,
  TabsCleanupIndexRoute: TabsCleanupIndexRoute,
}

const TabsCleanupRouteWithChildren = TabsCleanupRoute._addFileChildren(
  TabsCleanupRouteChildren,
)

interface TabsStorageRouteChildren {
  TabsStorageSplatRoute: typeof TabsStorageSplatRoute
  TabsStorageIndexRoute: typeof TabsStorageIndexRoute
}

const TabsStorageRouteChildren: TabsStorageRouteChildren = {
  TabsStorageSplatRoute: TabsStorageSplatRoute,
  TabsStorageIndexRoute: TabsStorageIndexRoute,
}

const TabsStorageRouteWithChildren = TabsStorageRoute._addFileChildren(
  TabsStorageRouteChildren,
)

interface TabsRouteChildren {
  TabsCleanupRoute: typeof TabsCleanupRouteWithChildren
  TabsInsightsRoute: typeof TabsInsightsRoute
  TabsStorageRoute: typeof TabsStorageRouteWithChildren
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsCleanupRoute: TabsCleanupRouteWithChildren,
  TabsInsightsRoute: TabsInsightsRoute,
  TabsStorageRoute: TabsStorageRouteWithChildren,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRoute: TabsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
